### ISSUE TITLE
error trying to run example code from README

### ISSUE THREAD

**Issue by CitizenEight** [tanema/talkies#3]
When I try to run this code from the readme: 

local Talkies = require('talkies')

function love.load()
  Talkies.new("Title", "Hello World!")
end

I get this error:
main.lua:4: attempt to call field 'new' (a nil value)
Traceback
main.lua:4: in function 'load'
[C]: in function 'xpcall'

**Comment by flamendless** [comment]
It's supposed to be 'say', not 'new'
